In [12]:
import numpy as np

# ✅ np.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0, like=None)

In [15]:
"""
📌 1. object (إجباري)
ده هو الداتا اللي بتحولها لمصفوفة.
ممكن تكون: list، tuple، list of lists، إلخ.
"""

'\n📌 1. object (إجباري)\nده هو الداتا اللي بتحولها لمصفوفة.\nممكن تكون: list، tuple، list of lists، إلخ.\n'

In [17]:
np.array([1, 2, 3])


array([1, 2, 3])

In [21]:
"""
🔴 لو ما كتبتوش؟ → Error: "missing required positional argument: 'object'"
"""

'\n🔴 لو ما كتبتوش؟ → Error: "missing required positional argument: \'object\'"\n'

In [25]:
"""
📌 2. dtype=None
نوع البيانات داخل المصفوفة (int, float, str, etc).
لو ما كتبتوش، Numpy بيحاول يختار نوع مناسب تلقائيًا.
"""

'\n📌 2. dtype=None\nنوع البيانات داخل المصفوفة (int, float, str, etc).\nلو ما كتبتوش، Numpy بيحاول يختار نوع مناسب تلقائيًا.\n'

In [27]:
np.array([1.5, 2.8], dtype=int)  # يحوّل القيم لأعداد صحيحة


array([1, 2])

In [29]:
"""
💥 خطأ ممكن يحصل؟ لو كتبت نوع غير متوافق مع القيم (مثلاً تحاول تحوّل نص إلى int)، هيديك Error.
"""

'\n💥 خطأ ممكن يحصل؟ لو كتبت نوع غير متوافق مع القيم (مثلاً تحاول تحوّل نص إلى int)، هيديك Error.\n'

In [31]:
"""
📌 3. copy=True
هل تعمل نسخة من الداتا الأصلية؟
True → يعمل نسخة مستقلة.
False → لو أمكن، يستخدم نفس البيانات في الذاكرة (أداء أفضل، بس أي تغيير هيأثر على الأصل).
"""

'\n📌 3. copy=True\nهل تعمل نسخة من الداتا الأصلية؟\nTrue → يعمل نسخة مستقلة.\nFalse → لو أمكن، يستخدم نفس البيانات في الذاكرة (أداء أفضل، بس أي تغيير هيأثر على الأصل).\n'

In [37]:
a = [1, 2, 3]
b = np.array(a, copy=False)
"""
لو عدّلت في(b) 
هتتغيّر a كمان!
"""

'\nلو عدّلت في(b) \nهتتغيّر a كمان!\n'

In [53]:
# Example with copy=True (creates a new copy)
a = np.array([1, 2, 3])
b = np.array(a, copy=True)
b[0] = 99
print(a) 
print(b)  


[1 2 3]
[99  2  3]


In [57]:
# Example with copy=False (uses the same memory if possible)
a = np.array([1, 2, 3])
b = np.array(a, copy=False)
b[0] = 99
print(a) 
print(b)

[99  2  3]
[99  2  3]


In [39]:
"""
(ترتيب البيانات في الذاكرة)
"تخيّل عندك جدول بيانات (زي إكسيل)، فيه صفوف وأعمدة. تخزين البيانات ممكن يتم صف بصف، أو عمود بعمود.
 يعني: خزن القيم عمود عمود، زي ما الإكسيل بيقرا العمود الأول كله وبعدين يروح للي بعده."
 "زي ما لما بتكتب على ورقة:
لو كتبت بالعرض ← ده اسمه
C-style (الافتراضي).
لو كتبت بالطول ← ده اسمه 
F-style."

📌 4. order='K'
ترتيب التخزين في الذاكرة.

'C' → row-major (صفوف أولاً).

'F' → column-major (أعمدة أولاً).

'K' → خليها زي ما هي موجودة.

✔️ الشكل الخارجي ما بيتغيرش.
الفرق الحقيقي في طريقة تخزين القيم داخل الذاكرة، وده بيأثر في حاجتين:

الأداء لو استخدمتِها في عمليات كثيرة أو تكرارية.

التكامل مع برامج أو مكتبات بتتوقع ترتيب معين (زي Fortran).
🔍 كيف تعرف طريقة التخزين؟
a.flags

"""

"\n📌 4. order='K'\nترتيب التخزين في الذاكرة.\n\n'C' → row-major (صفوف أولاً).\n\n'F' → column-major (أعمدة أولاً).\n\n'K' → خليها زي ما هي موجودة.\n"

In [65]:
a = np.array([[1, 2], [3, 4]], order='F')

In [67]:
a

array([[1, 2],
       [3, 4]])

In [71]:
a.flags

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

In [43]:
"""
⚠️ ما يأثرش على الشكل اللي بتشوفه، لكن ممكن يأثر على الأداء مع العمليات الكبيرة.
"""

'\n⚠️ ما يأثرش على الشكل اللي بتشوفه، لكن ممكن يأثر على الأداء مع العمليات الكبيرة.\n'

In [45]:
"""
📌 5. subok=False
هل تستخدم subclass من ndarray لو الداتا الأصلية كانت كده؟

False → دايمًا ترجّع ndarray عادية.

True → ممكن ترجّع subclass (لو موجودة).

مش مهم للمبتدئين، إلا في المكتبات المتقدّمة.
"""

'\n📌 5. subok=False\n📌 5. subok=False\nهل تستخدم subclass من ndarray لو الداتا الأصلية كانت كده؟\n\nFalse → دايمًا ترجّع ndarray عادية.\n\nTrue → ممكن ترجّع subclass (لو موجودة).\n\n🔹 مثال:\nمش مهم للمبتدئين، إلا في المكتبات المتقدّمة.\n'

In [ ]:
"""
📌 6. ndmin=0
الحد الأدنى لعدد الأبعاد.

مثلاً: ndmin=3 يخلي الشكل (1, 1, 3)

In [47]:
np.array([1, 2, 3], ndmin=2)

array([[1, 2, 3]])

In [59]:
"""
📌 7. like=None
📌 يعني إيه؟
دي ميزة جديدة ظهرت من إصدار 
NumPy 1.20.
بتقول لبايثون: "أنا عايزة الـ
array
الجديد يشبه نوع معين أو خصائص معينة من 
array
تانية."

مش المقصود هنا القيم، المقصود النوع أو الشكل أو النوع الخاص 
(subclass)
.مش مهم للمبتدئين حالياً
"""

'\n📌 7. like=None\n📌 يعني إيه؟\nدي ميزة جديدة ظهرت من إصدار \nNumPy 1.20.\nبتقول لبايثون: "أنا عايزة الـ\narray\nالجديد يشبه نوع معين أو خصائص معينة من \narray\nتانية."\n\nمش المقصود هنا القيم، المقصود النوع أو الشكل أو النوع الخاص \n(subclass)\n.مش مهم للمبتدئين حالياً\n'

In [61]:
import numpy as np

ref = np.matrix([[1, 2], [3, 4]])  # matrix مش array عادية
a = np.array([[5, 6], [7, 8]], like=ref)

print(type(a))  # <class 'numpy.matrixlib.defmatrix.matrix'> → نفس نوع ref


<class 'numpy.ndarray'>


In [63]:
"""
copy = "هل تنسخي ولا لأ؟"

like = "هل تخلي الشكل شبه حاجة تانية؟"
"""

'\ncopy = "هل تنسخي ولا لأ؟"\n\nlike = "هل تخلي الشكل شبه حاجة تانية؟"\n'

-------------------------------------------------------------------------------------------------------

# np.arange(start, stop, step, dtype=None, like=None)


In [78]:
"""
تُستخدم لإنشاء مصفوفة من القيم الرقمية في نطاق معين، مشابهة لدالة
range()
في 
python
لكن بترجع 
NumPy array
بدل ما ترجع 
range object
"""

'\nتُستخدم لإنشاء مصفوفة من القيم الرقمية في نطاق معين، مشابهة لدالة\nrange()\nفي \npython\nلكن بترجع \nNumPy array\nبدل ما ترجع \nrange object\n'

In [80]:
a = np.arange(5)
print(a)


[0 1 2 3 4]


In [82]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [84]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [86]:
np.arange(1, 5, dtype=float)

array([1., 2., 3., 4.])

In [88]:
np.arange(10, 2, -1)

array([10,  9,  8,  7,  6,  5,  4,  3])

In [96]:
np.arange(1, 4, dtype=float)	

array([1., 2., 3.])

In [90]:
np.arange()

TypeError: arange() requires stop to be specified.

In [92]:
np.arange(1, 5, 0)

ZeroDivisionError: division by zero

In [94]:
"""
💡 ملحوظة:
np.arange() ممتازة لما تكوني عايزة تسلسلات ثابتة، لكن أحيانًا بتكون غير دقيقة مع الأعداد العشرية → في الحالة دي ممكن تستخدمي np.linspace() لأنها أكثر دقة.
"""


'\n💡 ملحوظة:\nnp.arange() ممتازة لما تكوني عايزة تسلسلات ثابتة، لكن أحيانًا بتكون غير دقيقة مع الأعداد العشرية → في الحالة دي ممكن تستخدمي np.linspace() لأنها أكثر دقة.\n'

---------------------------------------------------

# np.zeros(shape, dtype=float, order='C', like=None)


In [104]:
"""
هي دالة من مكتبة
NumPy 
تُستخدم لإنشاء مصفوفة 
(Array) 
تحتوي فقط على أصفار 
(0s) 
بالحجم والشكل اللي إنتِ تحدديه.
"""


'\nهي دالة من مكتبة\nNumPy \nتُستخدم لإنشاء مصفوفة \n(Array) \nتحتوي فقط على أصفار \n(0s) \nبالحجم والشكل اللي إنتِ تحدديه.\n'

In [106]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [108]:
"""
النوع الافتراضي 
float.
"""

'\nالنوع الافتراضي \nfloat.\n'

In [110]:
np.zeros((3, 2))


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [112]:
np.zeros((2, 2, 3))


array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [114]:
np.zeros(4, dtype=int)


array([0, 0, 0, 0])

In [116]:
np.zeros((2, 3), order='F')


array([[0., 0., 0.],
       [0., 0., 0.]])

In [118]:
np.zeros()


TypeError: zeros() missing required argument 'shape' (pos 0)

In [120]:
np.zeros('3')


TypeError: 'str' object cannot be interpreted as an integer

In [124]:
"""
اعملي 
Matrix 2D
تمثل بيانات فارغة (مثلاً جدول درجات، لسه لم يتم ملؤه).

"""

'\nاعملي \nMatrix 2D\nتمثل بيانات فارغة (مثلاً جدول درجات، لسه لم يتم ملؤه).\n\npython\nCopy\nEdit\n'

In [126]:
grades = np.zeros((5, 3), dtype=int)
print("Initial Grades Table:\n", grades)


Initial Grades Table:
 [[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]


-------------------------------------

# np.ones(shape, dtype=float, order='C', *, like=None)


In [130]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [132]:
np.ones((3, 2))


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [134]:
np.ones((2, 2, 2))


array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [136]:
np.ones((2, 2), dtype=int)


array([[1, 1],
       [1, 1]])

In [138]:
# 🔹 الشكل الخارجي مش بيتغير، لكن التخزين الداخلي بيكون عمودي بدل من صفّي.

np.ones((2, 3), order='F')


array([[1., 1., 1.],
       [1., 1., 1.]])

In [140]:
np.ones()


TypeError: ones() missing 1 required positional argument: 'shape'

In [142]:
np.ones('3')


TypeError: 'str' object cannot be interpreted as an integer

In [144]:
"""
اعملي جدول حضور ابتدائي، كأن كل الطلاب حضروا، فتعملي مصفوفة فيها
"""

'\nاعملي جدول حضور ابتدائي، كأن كل الطلاب حضروا، فتعملي مصفوفة فيها\n'

In [146]:
attendance = np.ones((4, 3), dtype=bool)
print("Attendance Table:\n", attendance)


Attendance Table:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [148]:
#كل True معناها إن الطالب "حضَر".



-----------------

# np.full(shape, fill_value, dtype=None, order='C', like=None)


In [155]:
np.full(4, 7)


array([7, 7, 7, 7])

In [157]:
np.full((3, 2), 0)


array([[0, 0],
       [0, 0],
       [0, 0]])

In [159]:
np.full((2, 2), 5, dtype=float)


array([[5., 5.],
       [5., 5.]])

In [161]:
np.full((2, 3), True, dtype=bool)


array([[ True,  True,  True],
       [ True,  True,  True]])

In [163]:
np.full((2, 2), 'AI')


array([['AI', 'AI'],
       ['AI', 'AI']], dtype='<U2')

In [165]:
np.full((2, 2))  # Error!


TypeError: full() missing 1 required positional argument: 'fill_value'

In [169]:
"""
 مصفوفة تمثل نتيجة امتحان لطلاب، كلهم جايبين 50 درجة كبداية
"""

'\n مصفوفة تمثل نتيجة امتحان لطلاب، كلهم جايبين 50 درجة كبداية\n'

In [171]:
scores = np.full((5,), 50)
print("Initial Scores:", scores)


Initial Scores: [50 50 50 50 50]


---------------------------

# np.random.rand(d0, d1, ..., dn)


In [177]:
"""
📌 جميع المدخلات (arguments) هي أعداد صحيحة تمثل شكل المصفوفة المطلوبة.
"""


'\n📌 جميع المدخلات (arguments) هي أعداد صحيحة تمثل شكل المصفوفة المطلوبة.\n'

In [179]:
np.random.rand()


0.36933249065773355

In [181]:
np.random.rand(5)


array([0.03139308, 0.91736749, 0.56578734, 0.06590736, 0.30276937])

In [183]:
np.random.rand(3, 2)


array([[0.86417626, 0.31747673],
       [0.48264337, 0.11097799],
       [0.94134905, 0.5758681 ]])

In [185]:
np.random.rand(2, 2, 3)


array([[[0.17329351, 0.31094534, 0.88769241],
        [0.03555132, 0.37259923, 0.38360192]],

       [[0.25723662, 0.91373962, 0.46449754],
        [0.20492049, 0.99460542, 0.12155184]]])

In [187]:
np.random.rand((3, 4))  # ❌ خطأ


TypeError: 'tuple' object cannot be interpreted as an integer

In [189]:
np.random.rand(3, 4)  # ✅ بدون أقواس


array([[0.01885186, 0.85851273, 0.1315302 , 0.22964444],
       [0.87496977, 0.03140221, 0.78007362, 0.6357699 ],
       [0.3986822 , 0.52920747, 0.95773113, 0.89596845]])

In [191]:
#توليد بيانات درجات طلاب في امتحان

In [195]:
grades = np.random.rand(10) * 100  # عشوائية بين 0 و 100
grades = np.round(grades, 2)       # تقرب إلى منزلتين عشريتين


In [197]:
print("Grades:", grades)


Grades: [39.42 26.95 91.13 38.53 17.17 47.41  5.02 12.03 10.25 99.99]


----------------------

# numpy.random.randn(d0, d1, ..., dn)


In [205]:
"""
np.random.randn returns a NumPy array of shape (d0, d1, ..., dn) filled with random samples drawn from the standard normal distribution:

Mean = 0, Standard deviation = 1

This is also known as the "standard Gaussian distribution."

🔹 These are positional-only arguments and must be passed separately, not as a tuple.


"""

'\nnp.random.randn returns a NumPy array of shape (d0, d1, ..., dn) filled with random samples drawn from the standard normal distribution:\n\nMean = 0, Standard deviation = 1\n\nThis is also known as the "standard Gaussian distribution."\n\n🔹 These are positional-only arguments and must be passed separately, not as a tuple.\n\n\n'

In [211]:
# Single random value from N(0, 1)

x = np.random.randn()


In [213]:
x

-0.973958176270473

In [215]:
# 1D array of 5 samples
arr1 = np.random.randn(5)

In [217]:
arr1

array([ 0.4111243 , -1.01221158, -0.59342218,  2.93997271,  0.24379425])

In [219]:
# 2D array (3 rows, 4 columns)
arr2 = np.random.randn(3, 4)

In [221]:
arr2

array([[ 1.16550894,  0.020172  ,  0.1241926 ,  0.28410124],
       [-1.44419182,  0.25217383,  0.78486499,  0.38187472],
       [-1.42829529,  0.66269119,  0.8087424 ,  0.76342793]])

In [223]:
# 3D array (2 blocks, 3 rows, 2 columns)
arr3 = np.random.randn(2, 3, 2)

In [225]:
arr3

array([[[ 1.66998408, -0.74081017],
        [ 1.05834445, -0.44737422],
        [-0.19756632, -1.34794242]],

       [[ 0.21711517,  0.79907101],
        [ 0.65577716,  0.59641442],
        [-0.22307136, -0.44295343]]])

In [227]:
arr = np.random.randn((3, 4))  # ❌


TypeError: 'tuple' object cannot be interpreted as an integer

---------------------

# numpy.reshape(old_array, newshape, order='C')
# old_array.reshape(newshape, order='C')


In [233]:
"""
reshape() returns a new view (or sometimes a copy) of the array with a different shape, without changing the data.
"""


'\nreshape() returns a new view (or sometimes a copy) of the array with a different shape, without changing the data.\n'

In [235]:
arr = np.array([1, 2, 3, 4, 5, 6])


In [237]:
# Reshape to 2 rows, 3 columns
reshaped = arr.reshape(2, 3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [239]:
# Automatically infer one dimension using -1
reshaped_auto = arr.reshape(-1, 2)
print(reshaped_auto)

[[1 2]
 [3 4]
 [5 6]]


In [243]:
np.array([1, 2, 3, 4]).reshape(3, 2)  # ❌ Error


ValueError: cannot reshape array of size 4 into shape (3,2)

In [245]:
np.array([1, 2, 3, 4, 5, 6]).reshape(2, -1)  # → shape becomes (2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [251]:
"""
Machine Learning – 
تحويل البيانات لـ 
(samples, features)
📌 السبب:

معظم موديلات ML 
تتوقع بيانات في شكل
(عدد العينات, عدد الخصائص).


"""

'\nMachine Learning – \nتحويل البيانات لـ \n(samples, features)\n📌 السبب:\n\nمعظم موديلات ML \nتتوقع بيانات في شكل\n(عدد العينات, عدد الخصائص).\n\n\n'

In [253]:
# بيانات 6 عينات كل واحدة فيها 2 ميزة → الآن في شكل 1D
data = np.array([1, 2, 3, 4, 5, 6])

# نحتاج نعيد تشكيلها عشان تناسب مدخلات الموديل
reshaped = data.reshape(3, 2)

print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [256]:
"""
التعامل مع الصور 
(Image Processing)
📌 السبب:
للتعامل مع الصور، لازم تكون المصفوفة
2D 

3D

في حالة الصور الملونة 
RGB).


"""

'\nالتعامل مع الصور \n(Image Processing)\n\n'

In [258]:
# تخيلي عندك صورة رمادية 4x4 ممثلة في مصفوفة 1D
flat_image = np.array([0, 255, 100, 50, 200, 150, 80, 90, 255, 10, 0, 60, 70, 80, 90, 100])

# نعيد تشكيلها إلى صورة 2D
image = flat_image.reshape(4, 4)

print(image)


[[  0 255 100  50]
 [200 150  80  90]
 [255  10   0  60]
 [ 70  80  90 100]]


In [264]:
"""
لتجهيز بيانات
Time Series 
لشبكات 
RNN
📌 السبب:
الشبكات العصبية التكرارية تتطلب بيانات في شكل معين: 
(batch, time_step, feature).


"""

'\nلتجهيز بيانات\nTime Series \nلشبكات \nRNN\n📌 السبب:\nالشبكات العصبية التكرارية تتطلب بيانات في شكل معين: \n(batch, time_step, feature).\n\n\n'

In [266]:
# عندي بيانات لـ 10 أيام كل يوم في 5 قياسات
time_series = np.arange(50)  # array([0, 1, 2, ..., 49])

# الشكل المطلوب لـ RNN: (عينات, توقيت, خصائص)
reshaped = time_series.reshape(10, 1, 5)

print(reshaped.shape)  # (10, 1, 5)


(10, 1, 5)


"""
Flattening 
مصفوفة قبل تمريرها إلى موديل
"""

In [274]:
img = np.array([[0, 255], [100, 200]])
"""
نفردها إلى
1D 
قبل استخدامها في موديل
flattened = img.reshape(-1)
"""
print(flattened)



[  0 255 100 200]


---------------------

# np.resize(a, new_shape)


In [278]:
"""
np.resize()
بتغيّر شكل المصفوفة حسب 
new_shape.
لكن لو الشكل الجديد أكبر من عدد العناصر الموجودين → هتبدأ تكرّر البيانات لحد ما تكمّل الحجم الجديد.
"""

'\nnp.resize()\nبتغيّر شكل المصفوفة حسب \nnew_shape.\nلكن لو الشكل الجديد أكبر من عدد العناصر الموجودين → هتبدأ تكرّر البيانات لحد ما تكمّل الحجم الجديد.\n'

In [280]:
a = np.array([1, 2, 3])
b = np.resize(a, (2, 5))

print(b)

[[1 2 3 1 2]
 [3 1 2 3 1]]


In [282]:
a = np.array([10, 20, 30, 40, 50])
b = np.resize(a, (2, 2))

print(b)


[[10 20]
 [30 40]]


In [284]:
a = np.array([1, 2, 3, 4, 5])
a.resize((3, 2))  # بتغير المصفوفة نفسها
print(a)


[[1 2]
 [3 4]
 [5 0]]


In [286]:
"""
⚠️ متى تحصل على 
Error؟
لو استخدمت .
resize() method 
على 
array 
مستخدمة بالفعل في مكان آخر أو مش قابلة للتعديل في المكان → هتحصل على:
"""

SyntaxError: incomplete input (969763094.py, line 1)

In [288]:
"""
تجهيز بيانات لتعبئة واجهة أو 
Grid 
ثابتة الحجم
أنتِ بتطوّري واجهة لعرض صور أو بيانات في شبكة 
(Grid) 
مكونة من 3 صفوف × 4 أعمدة = 12 مكان
لكن البيانات اللي عندك أقل (مثلاً: 5 عناصر فقط)،
وعايزة تكمّلي الشكل.
الحل:
تستخدمي np.resize() لتكرار البيانات تلقائيًا وتعبئة الشبكة.

"""

'\nتجهيز بيانات لتعبئة واجهة أو \nGrid \nثابتة الحجم\nأنتِ بتطوّري واجهة لعرض صور أو بيانات في شبكة \n(Grid) \nمكونة من 3 صفوف × 4 أعمدة = 12 مكان\nلكن البيانات اللي عندك أقل (مثلاً: 5 عناصر فقط)،\nوعايزة تكمّلي الشكل.\n'

In [290]:
data = np.array(["A", "B", "C", "D", "E"])
grid_data = np.resize(data, (3, 4))

print(grid_data)

[['A' 'B' 'C' 'D']
 ['E' 'A' 'B' 'C']
 ['D' 'E' 'A' 'B']]


In [292]:
# البيانات اتكررت عشان تكمّل الشكل المطلوب، مثالي لواجهات المستخدم أو النماذج التفاعلية.

In [300]:
"""
تجربة نموذج 
ML 
يتطلب شكل بيانات ثابت
عندك نموذج 
Machine Learning 
بيتوقع على بيانات حجمها دائمًا (100,)،
لكن البيانات اللي وصلتك 80 عنصر فقط.
ممكن تستخدم 
resize 
لتكرار البيانات بدل ما ترميها أو تضيف أصفار
مفيد في التجارب السريعة أو النماذج البسيطة (لكن لازم تنتبهي إن التكرار مش دايمًا أفضل خيار في النماذج النهائية)
"""


'\nتجربة نموذج \nML \nيتطلب شكل بيانات ثابت\nعندك نموذج \nMachine Learning \nبيتوقع على بيانات حجمها دائمًا (100,)،\nلكن البيانات اللي وصلتك 80 عنصر فقط.\nممكن تستخدم \nresize \nلتكرار البيانات بدل ما ترميها أو تضيف أصفار\nمفيد في التجارب السريعة أو النماذج البسيطة (لكن لازم تنتبهي إن التكرار مش دايمًا أفضل خيار في النماذج النهائية)\n'

In [302]:
x = np.array(range(80))  # بيانات ناقصة
x_fixed = np.resize(x, 100)

print(x_fixed.shape)  


(100,)


In [304]:
"""
تطبيق في تحليل النصوص 
(NLP)
جالك نصوص (مثل تغريدات) مختلفة في الطول، لكن النموذج بتاعك محتاج كل نص يكون طوله 50 حرف.
ممكن تحولي النص لـ
array
من الأرقام (أو الأكواد)، وتستخدمي
resize()
لضبط الطول المطلوب.
"""





'\nتطبيق في تحليل النصوص \n(NLP)\nجالك نصوص (مثل تغريدات) مختلفة في الطول، لكن النموذج بتاعك محتاج كل نص يكون طوله 50 حرف.\nممكن تحولي النص لـ\narray\nمن الأرقام (أو الأكواد)، وتستخدمي\nresize()\nلضبط الطول المطلوب.\n'

In [306]:
text_vector = np.array([1, 4, 6, 7, 2])  # تمثيل لنص قصير
fixed_text = np.resize(text_vector, 50)

print(fixed_text)


[1 4 6 7 2 1 4 6 7 2 1 4 6 7 2 1 4 6 7 2 1 4 6 7 2 1 4 6 7 2 1 4 6 7 2 1 4
 6 7 2 1 4 6 7 2 1 4 6 7 2]


----------------------

# np.copy(a, order='K', subok=True)


In [310]:
"""
➤ np.copy()
تستخدم لإنشاء نسخة مستقلة تمامًا 
(deep copy) 
من المصفوفة الأصلية.
يعني:

التعديلات على النسخة الجديدة لا تؤثر على الأصل.

ودي حاجة مهمة لو مش عايزة تخسري البيانات الأصلية.



"""


'\n➤ np.copy()\nتستخدم لإنشاء نسخة مستقلة تمامًا \n(deep copy) \nمن المصفوفة الأصلية.\nيعني:\n\nالتعديلات على النسخة الجديدة لا تؤثر على الأصل.\n\nودي حاجة مهمة لو مش عايزة تخسري البيانات الأصلية.\n\n\n\n'

In [312]:
a = np.array([1, 2, 3])
b = np.copy(a)

b[0] = 99

print("Original:", a)  
print("Copy:    ", b) 

Original: [1 2 3]
Copy:     [99  2  3]


In [314]:
# تعديل b لم يؤثر على a.



In [316]:
#❗ الفرق بين copy() و = (assignment)


In [318]:
a = np.array([1, 2, 3])
b = a        # هذا مجرد مرجع (reference)

b[0] = 99

print("a:", a)  # ➤ [99 2 3] ← تأثر!


a: [99  2  3]


In [320]:
"""
b = a ← مجرد مرجع لنفس المكان في الذاكرة.

b = np.copy(a) ← نسخة مستقلة تمامًا.
"""

'\nb = a ← مجرد مرجع لنفس المكان في الذاكرة.\n\nb = np.copy(a) ← نسخة مستقلة تمامًا.\n'

In [322]:
"""
🔄 الفرق بين 
copy() 
و 
deepcopy() 
في بايثون العادي:
np.copy() = deep copy لمصفوفة numpy فقط.

copy.deepcopy() = نسخ عميق لأي كائن في بايثون (حتى المتداخلين).
"""

'\n🔄 الفرق بين \ncopy() \nو \ndeepcopy() \nفي بايثون العادي:\nnp.copy() = deep copy لمصفوفة numpy فقط.\n\ncopy.deepcopy() = نسخ عميق لأي كائن في بايثون (حتى المتداخلين).\n'

In [324]:
"""
🔄 الفرق بين 
np.copy() 
و
copy.deepcopy() 
في التعامل مع ده:
1. np.copy():
تنسخ مصفوفة 
numpy 
بس
حتى لو جواها أشياء متداخلة، مش دايمًا تقدر تتعامل مع كل الأعماق.

2. copy.deepcopy():
من مكتبة 
copy 
في بايثون.

بتعمل نسخ عميق لكل حاجة جوا الكائن مهما كان متداخل.
"""

'\n🔄 الفرق بين \nnp.copy() \nو\ncopy.deepcopy() \nفي التعامل مع ده:\n1. np.copy():\nتنسخ مصفوفة \nnumpy \nبس\nحتى لو جواها أشياء متداخلة، مش دايمًا تقدر تتعامل مع كل الأعماق.\n\n2. copy.deepcopy():\nمن مكتبة \ncopy \nفي بايثون.\n\nبتعمل نسخ عميق لكل حاجة جوا الكائن مهما كان متداخل.\n'

In [326]:
import copy

original = [[1, 2], [3, 4]]
shallow = original.copy()

shallow[0][0] = 999

print(original)  # ➤ [[999, 2], [3, 4]] ← اتغيّر الأصل!


[[999, 2], [3, 4]]


In [328]:
deep = copy.deepcopy(original)

deep[0][0] = 111

print(original)  # ➤ [[1, 2], [3, 4]] ← سليم، مفيش تغيّر
print(deep)      # ➤ [[111, 2], [3, 4]]


[[999, 2], [3, 4]]
[[111, 2], [3, 4]]


In [330]:
"""
مشروع تحليل بيانات طلاب، وفيه مصفوفة 
Numpy 
اسمها 
grades_array
استخدام 
np.copy()
او
copy.deepcopy()
"""




'\nمشروع تحليل بيانات طلاب، وفيه مصفوفة \nNumpy \nاسمها \ngrades_array\nاستخدام \nnp.copy()\nاو\ncopy.deepcopy()\n'

In [332]:
"""
بيانات بسيطة من نوع 
NumPy Array 
(غير متداخلة)
نستخدم 
np.copy()
"""

'\nبيانات بسيطة من نوع \nNumPy Array \n(غير متداخلة)\nنستخدم \nnp.copy()\n'

In [334]:
grades_array = np.array([80, 90, 70, 85])

# نعمل نسخة منها للتعديل:
copy_grades = np.copy(grades_array)

copy_grades[0] = 100

print("Original:", grades_array)  
print("Copy:", copy_grades)    

Original: [80 90 70 85]
Copy: [100  90  70  85]


In [336]:
"""
بيانات متداخلة 
(قائمة جواها مصفوفات – Nested)
"""

'\nبيانات متداخلة \n(قائمة جواها مصفوفات – Nested)\n'

In [338]:
nested_data = [[np.array([80, 90])], [np.array([70, 85])]]

# shallow copy (مش هتنفع هنا)
shallow = nested_data.copy()

shallow[0][0][0] = 999  # تعديل العنصر الأول

print(nested_data)  # ❌ الأصل اتغير!

[[array([999,  90])], [array([70, 85])]]


In [342]:
deep = copy.deepcopy(nested_data)
deep[0][0][0] = 555

print(nested_data)  # ✅ سليم، مفيش تغيير
print(deep)         # ✅ النسخة اتعدلت لوحدها


[[array([999,  90])], [array([70, 85])]]
[[array([555,  90])], [array([70, 85])]]


# array[start:stop:step]
# slicing

In [346]:
"""
Slicing 
يعني تقطيع جزء من مصفوفة أو استخراج جزء منها باستخدام الفهارس 
(indexes).

هو زي ما تقولي:

"هاتلي الصف الأول"، أو "هات العمود التاني"، أو "هات القيم من العنصر رقم 2 إلى 5".
"""

'\nSlicing \nيعني تقطيع جزء من مصفوفة أو استخراج جزء منها باستخدام الفهارس \n(indexes).\n\nهو زي ما تقولي:\n\n"هاتلي الصف الأول"، أو "هات العمود التاني"، أو "هات القيم من العنصر رقم 2 إلى 5".\n'

In [348]:
a = np.array([10, 20, 30, 40, 50, 60])

print(a[1:4])    
print(a[:3])       
print(a[3:])     
print(a[::2])    
print(a[::-1])    

[20 30 40]
[10 20 30]
[40 50 60]
[10 30 50]
[60 50 40 30 20 10]


In [358]:
b = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [360]:
print(b[0])         


[1 2 3]


In [362]:
print(b[:, 1])      


[2 5 8]


In [364]:
print(b[1:, :2])

[[4 5]
 [7 8]]


In [369]:
"""
✅ 1. معالجة الصور
(Image Processing):
📌 الموقف:
عندك صورة كمصفوفة 
(مثلاً 256x256 بكسل)، 
وعايزة تقتصي جزء منها 
(crop).
🟡 فايدة 
slicing 
هنا:
بتسمحلك تعملي 
Crop 
للصورة بسهولة بدون مكتبات إضافية.


"""

'\n✅ 1. معالجة الصور\n(Image Processing):\n📌 الموقف:\nعندك صورة كمصفوفة \n(مثلاً 256x256 بكسل)، \nوعايزة تقتصي جزء منها \n(crop).\n🟡 فايدة \nslicing \nهنا:\nبتسمحلك تعملي \nCrop \nللصورة بسهولة بدون مكتبات إضافية.\n\n\n'

In [371]:
image = np.random.rand(256, 256)  # صورة رمادية عشوائية

cropped = image[50:150, 50:150]   # اقتصاص مربع 100x100 من وسط الصورة


In [373]:
image

array([[0.23139966, 0.47356401, 0.59064111, ..., 0.9569421 , 0.48732431,
        0.06364581],
       [0.31910234, 0.02822131, 0.58397318, ..., 0.82309206, 0.45447796,
        0.17229329],
       [0.24279764, 0.35814974, 0.5560948 , ..., 0.84540596, 0.59419747,
        0.64127361],
       ...,
       [0.88772542, 0.9522379 , 0.03211408, ..., 0.04719192, 0.04298979,
        0.72067052],
       [0.66853109, 0.27018896, 0.41011278, ..., 0.93085045, 0.50725427,
        0.0026281 ],
       [0.20262718, 0.11325635, 0.35238748, ..., 0.79325577, 0.06856263,
        0.44548902]])

In [375]:
cropped

array([[0.28869908, 0.52507851, 0.06947054, ..., 0.7653671 , 0.09755828,
        0.6436763 ],
       [0.56997811, 0.36359437, 0.80511516, ..., 0.03043024, 0.31095974,
        0.7857913 ],
       [0.87819126, 0.52531376, 0.78103853, ..., 0.67475318, 0.88974442,
        0.32434581],
       ...,
       [0.04419405, 0.36031513, 0.77652092, ..., 0.78737309, 0.01077147,
        0.36301993],
       [0.74877714, 0.66664818, 0.56151916, ..., 0.88937969, 0.39825084,
        0.73627573],
       [0.07930363, 0.13082505, 0.75917304, ..., 0.12789872, 0.54540539,
        0.43907718]])

In [381]:
"""
✅ 2. تقسيم البيانات (Train/Test Split):
📌 الموقف: عندك بيانات (مثلاً 1000 سجل)، وعايزة تقسّميهم 80% للتدريب و20% للاختبار.
🟡 فايدة 
slicing: 
أسرع طريقة لتقسيم البيانات.


"""

'\n✅ 2. تقسيم البيانات (Train/Test Split):\n📌 الموقف: عندك بيانات (مثلاً 1000 سجل)، وعايزة تقسّميهم 80% للتدريب و20% للاختبار.\n🟡 فايدة \nslicing: \nأسرع طريقة لتقسيم البيانات.\n\n\n'

In [379]:
data = np.arange(1000)

train = data[:800]
test = data[800:]


In [387]:
"""
✅ 3. معالجة سلاسل زمنية 
(Time Series):
📌 الموقف: بناء نافذة متحركة 
(moving window) 
لتحليل بيانات.



"""

'\n✅ 3. معالجة سلاسل زمنية \n(Time Series):\n📌 الموقف: بناء نافذة متحركة \n(moving window) \nلتحليل بيانات.\n\n\n\n'

In [389]:
series = np.array([1, 2, 3, 4, 5, 6, 7, 8])

for i in range(len(series) - 2):
    window = series[i:i+3]
    print(window)


[1 2 3]
[2 3 4]
[3 4 5]
[4 5 6]
[5 6 7]
[6 7 8]


In [391]:
"""
✅ 4. تحليل بيانات نصيّة (Text Tokenization):
📌 الموقف: عندك قائمة كلمات، وعايزة تبصي على جملة من كلمات معينة.
"""

'\n✅ 4. تحليل بيانات نصيّة (Text Tokenization):\n📌 الموقف: عندك قائمة كلمات، وعايزة تبصي على جملة من كلمات معينة.\n'

In [393]:
words = np.array(['I', 'love', 'data', 'science', 'so', 'much'])

phrase = words[1:4]


In [395]:
phrase

array(['love', 'data', 'science'], dtype='<U7')

In [399]:
"""

✅ 5. التعامل مع 
Batch في تعلم الآلة
(ML Batches):
📌 الموقف: إرسال دفعات بيانات للموديل.
"""

'\n\n✅ 5. التعامل مع \nBatch في تعلم الآلة\n(ML Batches):\n📌 الموقف: إرسال دفعات بيانات للموديل.\n'

In [401]:
X = np.random.rand(1000, 20)  # 1000 عينة، كل واحدة فيها 20 ميزة

batch = X[0:64]  


"""
✅  التعامل مع بيانات 
Multidimensional:
📌 الموقف: استخراج قناة معينة من صورة 
RGB (3 أبعاد).
"""

In [409]:
image_rgb = np.random.rand(128, 128, 3)

red_channel = image_rgb[:, :, 0]  # القناة الحمراء فقط


---------------------------

# np.random.permutation(x)


In [414]:
"""
np.random.permutation() 
ترجع نسخة مرتبة عشوائيًا 
(shuffled) من:

أرقام من 0 إلى 
n-1 
لو أعطيتها عددًا صحيحًا 
n.
أو نسخة 
shuffled من مصفوفة/قائمة/
array موجودة لو أعطيتها مصفوفة
"""

'\nnp.random.permutation() \nترجع نسخة مرتبة عشوائيًا \n(shuffled) من:\n\nأرقام من 0 إلى \nn-1 \nلو أعطيتها عددًا صحيحًا \nn.\nأو نسخة \nshuffled من مصفوفة/قائمة/\narray موجودة لو أعطيتها مصفوفة\n'

In [432]:
"""
✅ np.random.permutation()
بترجع نسخة جديدة من البيانات 
shuffled.
الأصل ما بيتغيرش.
✅ np.random.shuffle()
ما بترجعش حاجة 
(ترجع None).
لكن بتغير البيانات الأصلية نفسها 
(in-place).
"""


'\n✅ np.random.permutation()\nبترجع نسخة جديدة من البيانات \nshuffled.\nالأصل ما بيتغيرش.\n✅ np.random.shuffle()\nما بترجعش حاجة \n(ترجع None).\nلكن بتغير البيانات الأصلية نفسها \n(in-place).\n'

In [436]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([1, 2, 3, 4])

# permutation → نسخة جديدة
shuffled1 = np.random.permutation(arr1)
print("Original arr1:", arr1)        

print("Shuffled copy:", shuffled1)   


# shuffle → تعديل في الأصل
np.random.shuffle(arr2)
print("Shuffled in-place arr2:", arr2)  



Original arr1: [1 2 3 4]
Shuffled copy: [4 2 1 3]
Shuffled in-place arr2: [3 1 4 2]


In [420]:
# 🔹الهدف: إنشاء ترتيب عشوائي بدون تكرار من مجموعة أرقام.

np.random.permutation(5)

array([4, 3, 0, 1, 2])

In [422]:
arr = np.array([10, 20, 30, 40])
shuffled = np.random.permutation(arr)
print(shuffled)


[30 40 10 20]


In [426]:
# توزيع الأسئلة أو المهمات عشوائيًا

questions = ["Q1", "Q2", "Q3", "Q4"]
np.random.permutation(questions)


array(['Q4', 'Q2', 'Q1', 'Q3'], dtype='<U2')

In [430]:
# تحضير بيانات التدريب في ML:
X = np.array([[1], [2], [3], [4]])
X_shuffled = np.random.permutation(X)
X_shuffled

array([[3],
       [4],
       [2],
       [1]])

----------------------

# np.random.randint(low, high=None, size=None, dtype=int)


In [442]:
np.random.randint(10)

8

In [444]:
np.random.randint(5, 15, size=5)

array([ 6, 12, 10,  6, 13])

In [446]:
np.random.randint(1, 100, size=(2, 3))

array([[48, 61, 22],
       [91, 34, 52]])

In [448]:
"""
تحليل سلوك المستخدم في تطبيق تسوّق إلكتروني
عايزين نحاكي 
(simulate) 
بيانات مستخدمين
عشان ندرّب موديل يتوقع نوع المستخدم
(نشط / غير نشط).
"""


'\nتحليل سلوك المستخدم في تطبيق تسوّق إلكتروني\nعايزين نحاكي \n(simulate) \nبيانات مستخدمين\nعشان ندرّب موديل يتوقع نوع المستخدم\n(نشط / غير نشط).\n'

In [450]:
"""
نستخدم 
np.random.randint() 
لتوليد بيانات وهمية مثل:
عدد المرات اللي دخل فيها المستخدم التطبيق خلال الأسبوع

عدد المنتجات اللي شافها

عدد المرات اللي أضاف منتج إلى العربة

عدد المرات اللي أتم عملية شراء
"""

'\nنستخدم \nnp.random.randint() \nلتوليد بيانات وهمية مثل:\nعدد المرات اللي دخل فيها المستخدم التطبيق خلال الأسبوع\n\nعدد المنتجات اللي شافها\n\nعدد المرات اللي أضاف منتج إلى العربة\n\nعدد المرات اللي أتم عملية شراء\n'

In [452]:
import pandas as pd

# عدد المستخدمين اللي هنحاكيهم
n_users = 1000

# توليد البيانات
logins = np.random.randint(0, 20, size=n_users)          # عدد تسجيلات الدخول (0-20)
products_viewed = np.random.randint(1, 100, size=n_users)  # عدد المنتجات اللي شافها
add_to_cart = np.random.randint(0, 10, size=n_users)     # عدد المرات اللي ضاف منتج للعربة
purchases = np.random.randint(0, 5, size=n_users)        # عدد المشتريات

# إنشاء جدول البيانات
data = pd.DataFrame({
    'User_ID': np.arange(1, n_users + 1),
    'Logins': logins,
    'Products_Viewed': products_viewed,
    'Add_To_Cart': add_to_cart,
    'Purchases': purchases
})

print(data.head())


   User_ID  Logins  Products_Viewed  Add_To_Cart  Purchases
0        1      18               19            3          1
1        2      17               90            6          3
2        3      13               75            3          0
3        4      17               55            6          3
4        5       9               66            4          0


-------------------------------------------------------

# np.argwhere(condition)


In [458]:
"""
تعيد إحداثيات 
(indices) 
العناصر التي تحقق شرط معين داخل مصفوفة 
numpy
"""


'\nتعيد إحداثيات \n(indices) \nالعناصر التي تحقق شرط معين داخل مصفوفة \nnumpy\n'

In [460]:
import numpy as np

a = np.array([[10, 20], [30, 15]])

# نجيب أماكن العناصر الأكبر من 15
indices = np.argwhere(a > 15)

print(indices)


[[0 1]
 [1 0]]


In [464]:
"""
[0, 1] ← العنصر 20

[1, 0] ← العنصر 30
"""

'\n[0, 1] ← العنصر 20\n\n[1, 0] ← العنصر 30\n'

In [466]:
# 🤔 طيب ليه بنكتب [0][0] في بعض الأحيان؟


In [468]:
idx = np.argwhere(a == 20)[0][0]


In [472]:
idx # row index only

0

In [474]:
"""
📌 التفسير:

np.argwhere(a == 20) → [[0, 1]] (2D array)

[0] → أول نتيجة: [0, 1]

[0][0] → العنصر الأول في [0, 1] → 0 (الـ row index فقط)
"""

'\n📌 التفسير:\n\nnp.argwhere(a == 20) → [[0, 1]] (2D array)\n\n[0] → أول نتيجة: [0, 1]\n\n[0][0] → العنصر الأول في [0, 1] → 0 (الـ row index فقط)\n'

In [476]:
"""
🚨 ملاحظات:
النتيجة دائمًا تكون 2D حتى لو كان a 1D.

لو مفيش ولا عنصر بيحقق الشرط → النتيجة هتكون مصفوفة فاضية: array([], shape=(0, 2), dtype=int64)

"""

'\n🚨 ملاحظات:\nالنتيجة دائمًا تكون 2D حتى لو كان a 1D.\n\nلو مفيش ولا عنصر بيحقق الشرط → النتيجة هتكون مصفوفة فاضية: array([], shape=(0, 2), dtype=int64)\n\n'

In [478]:
"""
أنتِ بتشتغلي على تحليل بيانات طبية (مثلاً بيانات ضغط الدم لمجموعة من المرضى)، وعايزة تجهزي البيانات قبل ما تدربي نموذج تنبؤي
🎯 الهدف:
تحددي أماكن القيم المفقودة (NaN) أو

القيم المتطرفة (outliers) علشان:

تحذفيها

أو تعوضيها

أو تتخذي قرار بتنظيفها
"""

'\nأنتِ بتشتغلي على تحليل بيانات طبية (مثلاً بيانات ضغط الدم لمجموعة من المرضى)، وعايزة تجهزي البيانات قبل ما تدربي نموذج تنبؤي\n🎯 الهدف:\nتحددي أماكن القيم المفقودة (NaN) أو\n\nالقيم المتطرفة (outliers) علشان:\n\nتحذفيها\n\nأو تعوضيها\n\nأو تتخذي قرار بتنظيفها\n'

In [480]:
data = np.array([[120, 125], [np.nan, 140], [135, np.nan]])

# نستخدم np.isnan() عشان نحدد أماكن الـ NaN
nan_indices = np.argwhere(np.isnan(data))

print("Missing values found at:", nan_indices)


Missing values found at: [[1 0]
 [2 1]]


In [482]:
# تعريف: أي قيمة أكبر من 180 نعتبرها outlier
outliers = np.argwhere(data > 180)

print("Outliers at:", outliers)


Outliers at: []


In [ ]:
"""
لو بتشتغلي على بيانات صور 
(image data)، 
وعايزة تعملي 
mask
للأجزاء اللي فيها خلل (خلية بكسل قيمتها 0 مثلاً)، 
تقدري تستخدمي
: faulty_pixels = np.argwhere(image_data == 0)

"""